export const masterProductDefaultValues = {
  tradeName: '',
  scientificName: '',
  concentration: '',
  size: '',
  refPurchasePrice: 0,
  refSellingPrice: 0,
  notes: '',
  tax: 0,
  barcode: '',
  productType: 'MASTER' as const,
  requiresPrescription: false,
  typeId: 0,
  formId: 0,
  manufacturerId: 0,
  categories: [],
}; 